const COMMON_CONTEXT = Object.freeze([
  "botId",
  "personaId",
  "sessionKey",
  "requesterId",
  "guildId",
  "channelId",
  "voiceChannelId",
  "isDm",
  "permissions",
  "requestId",
  "deadline",
  "abortSignal",
]);

const ONE_OUTBOUND_OWNER = Object.freeze({
  owner: "current_bot_persona_output",
  toolSendsDiscordText: false,
  duplicateSuppression: "runtime_output_boundary",
});

function tool(entry) {
  return Object.freeze({
    registrationStatus: "active",
    registrationEvidence: "openclaw_active_plugin_contract",
    ...entry,
    request: Object.freeze({
      commonContext: COMMON_CONTEXT,
      ...entry.request,
    }),
    discord: Object.freeze({ ...ONE_OUTBOUND_OWNER, ...(entry.discord || {}) }),
  });
}

// This is descriptive metadata for the currently loaded registry. It does not
// route, authorize, rewrite, or execute a tool. Unknown bundled schemas stay
// explicitly UNVERIFIED instead of being inferred from a tool name.
export const TOOL_REGISTRY = Object.freeze([
  tool({
    toolId: "rana_analyze_image",
    pluginId: "rana-vision",
    purpose: "Resolve all visible image targets and return bounded identity evidence without changing the current bot persona.",
    request: { required: ["request_id"], optional: ["image_path", "channel_id", "reply_message_id", "prompt", "session_key"], schemaStatus: "RETRIEVED" },
    response: { kind: "structured", fields: ["requestId", "imageUnderstanding", "canonicalIdentity", "identityTargets", "responseContract"], rawMedia: false, rawEmbedding: false },
    state: { model: ["shared-resource", "session-scoped"], sharedState: true, isolation: ["requestId", "sessionKey", "currentBotSession"], personaIsolation: "current bot remains unchanged" },
    permissions: "Current agent tool policy plus an inbound/replied image; no identity-bank write.",
    timeout: { pipelineMs: 420000, vision03IdentityMs: 110000, identitySidecarMs: 30000, schemaStatus: "RETRIEVED" },
    errors: ["unknown", "unresolved", "unavailable", "timeout", "error"],
    dependency: ["Qwen3-VL at 6970", "identity sidecar at 6971", "local retrieval cache", "optional bounded reverse-search services"],
    contextGaps: ["botId", "personaId", "requesterId", "guildId", "voiceChannelId", "isDm", "permissions"],
    discord: { sideEffects: [], outputSchema: "rana.vision.tool-result.v1" },
  }),
  tool({
    toolId: "rana_memory",
    pluginId: "rana-runtime",
    purpose: "Explicit durable memory remember, recall, forget, or status operation.",
    request: { required: ["action", "text"], optional: ["requester_id"], schemaStatus: "RETRIEVED" },
    response: { kind: "structured", fields: ["status", "action", "result", "error"], rawPrivateCorpus: false },
    state: { model: ["persona-scoped", "session-scoped"], sharedState: true, isolation: ["botId", "personaId", "requesterId", "sessionKey"], namespace: "memory sidecar scope" },
    permissions: "Explicit durable-memory intent; delete and protected operations retain requester/role checks.",
    timeout: { sidecarMs: 15000, schemaStatus: "RETRIEVED" },
    errors: ["invalid_action", "forbidden", "unavailable", "timeout", "error"],
    dependency: ["hot-tools sidecar 8091 /memory/status|recall|remember|delete"],
  }),
  tool({
    toolId: "rana_lore_search",
    pluginId: "rana-runtime",
    purpose: "Read-only retrieval from the manifest-approved Rana LORE corpus.",
    request: { required: ["query"], optional: [], schemaStatus: "RETRIEVED" },
    response: { kind: "structured", fields: ["status", "sourceRefs", "evidence", "boundary"], rawCorpus: false },
    state: { model: ["shared-resource"], sharedState: true, isolation: ["query", "currentBotSession"], mutation: "read-only" },
    permissions: "Explicit character, relationship, event, or source question only.",
    timeout: { value: "UNVERIFIED: no explicit tool timeout in current registration" },
    errors: ["empty", "boundary", "unavailable", "error"],
    dependency: ["LORE manifest", "local controlled corpus"],
  }),
  tool({
    toolId: "rana_stock_research",
    pluginId: "rana-runtime",
    purpose: "Return structured US-stock research evidence for any trusted requester in a targeted Discord turn with explicit current-turn stock intent.",
    request: { required: ["query"], optional: ["tickers", "requester_id"], schemaStatus: "RETRIEVED" },
    response: { kind: "structured", fields: ["status", "decision_contract", "numbers_hash", "data", "error"], financialValuesImmutable: true },
    state: { model: ["shared-resource", "restricted"], sharedState: true, isolation: ["requesterId", "current-turn context"], cache: "shared sidecar/cache" },
    permissions: "Any trusted requester may use it in a targeted Discord turn with explicit current-turn stock intent; never places orders.",
    timeout: { sidecarMs: 60000, fallbackSidecarMs: 60000, schemaStatus: "RETRIEVED" },
    errors: ["forbidden", "abstain", "unavailable", "timeout", "error"],
    dependency: ["hot-tools sidecar 8091 /stock/research, legacy /api/hot-tools fallback"],
  }),
  tool({
    toolId: "persona_lore_search",
    pluginId: "rana-runtime",
    purpose: "Read-only query-specific retrieval from the active non-Rana persona LORE.",
    request: { required: ["query"], optional: [], schemaStatus: "RETRIEVED" },
    response: { kind: "structured", fields: ["status", "evidence", "sourceRefs", "boundary"], rawCorpus: false },
    state: { model: ["persona-scoped"], sharedState: true, isolation: ["personaId", "query", "currentBotSession"], mutation: "read-only" },
    permissions: "Explicit character, relationship, event, timeline, source, or setting question only.",
    timeout: { value: "UNVERIFIED: no explicit tool timeout in current registration" },
    errors: ["boundary", "empty", "unavailable", "error"],
    dependency: ["local persona Deep LORE corpus"],
  }),
  tool({
    toolId: "rana_play_music",
    pluginId: "rana-music-tools",
    purpose: "Queue and play music through the shared Discord voice pipeline.",
    request: { required: ["guild_id"], optional: ["url", "query", "source_text", "channel_id", "requester_id", "requester"], schemaStatus: "RETRIEVED" },
    response: { kind: "structured", fields: ["status", "queue", "current", "voice_status", "error"], textOwner: "current bot" },
    state: { model: ["shared-resource", "session-scoped"], sharedState: true, isolation: ["guildId", "voiceChannelId", "textChannelId", "requesterId", "queueOwner", "voiceConnectionOwner"] },
    permissions: "Explicit playback request and requester voice context.",
    timeout: { queueMs: 12000, playMs: 45000, playlistMs: 180000, schemaStatus: "RETRIEVED" },
    errors: ["missing_requester", "not_in_voice", "not_in_guild", "unavailable", "timeout", "error"],
    dependency: ["shared voice sidecar 8081", "YouTube/Bilibili source resolution"],
    contextGaps: ["botId", "personaId", "isDm", "permissions", "deadline"],
    discord: { sideEffects: ["shared voice queue", "voice connection"], outputSchema: "structured voice status" },
  }),
  tool({
    toolId: "rana_stop_music",
    pluginId: "rana-music-tools",
    purpose: "Stop shared playback while retaining the voice connection.",
    request: { required: ["guild_id"], optional: [], schemaStatus: "RETRIEVED" },
    response: { kind: "structured", fields: ["status", "voice_status", "error"] },
    state: { model: ["shared-resource"], sharedState: true, isolation: ["guildId", "queueOwner", "voiceConnectionOwner"] },
    permissions: "Current voice-control context.",
    timeout: { sidecarMs: 12000, schemaStatus: "RETRIEVED" },
    errors: ["unavailable", "timeout", "error"],
    dependency: ["shared voice sidecar 8081 /voice/stop"],
    contextGaps: ["botId", "personaId", "requesterId", "permissions"],
  }),
  tool({
    toolId: "rana_show_queue",
    pluginId: "rana-music-tools",
    purpose: "Read the shared music queue or refresh its Discord panel.",
    request: { required: ["guild_id"], optional: ["text_channel_id", "panel"], schemaStatus: "RETRIEVED" },
    response: { kind: "structured", fields: ["status", "queue", "current", "error"] },
    state: { model: ["shared-resource"], sharedState: true, isolation: ["guildId", "textChannelId", "queueOwner"] },
    permissions: "Current voice-control context.",
    timeout: { sidecarMs: 12000, schemaStatus: "RETRIEVED" },
    errors: ["unavailable", "timeout", "error"],
    dependency: ["shared voice sidecar 8081 /voice/queue|queue-panel"],
  }),
  tool({
    toolId: "rana_skip_music",
    pluginId: "rana-music-tools",
    purpose: "Skip the current song or remove a queued song.",
    request: { required: ["guild_id"], optional: ["query"], schemaStatus: "RETRIEVED" },
    response: { kind: "structured", fields: ["status", "queue", "current", "error"] },
    state: { model: ["shared-resource"], sharedState: true, isolation: ["guildId", "queueOwner", "voiceConnectionOwner"] },
    permissions: "Current voice-control context.",
    timeout: { sidecarMs: 12000, schemaStatus: "RETRIEVED" },
    errors: ["unavailable", "timeout", "error"],
    dependency: ["shared voice sidecar 8081 /voice/skip"],
  }),
  tool({
    toolId: "rana_volume_music",
    pluginId: "rana-music-tools",
    purpose: "Read or change shared playback volume.",
    request: { required: ["guild_id"], optional: ["volume", "delta"], schemaStatus: "RETRIEVED" },
    response: { kind: "structured", fields: ["status", "volume", "voice_status", "error"] },
    state: { model: ["shared-resource"], sharedState: true, isolation: ["guildId", "queueOwner"] },
    permissions: "Current voice-control context.",
    timeout: { sidecarMs: 12000, schemaStatus: "RETRIEVED" },
    errors: ["invalid_volume", "unavailable", "timeout", "error"],
    dependency: ["shared voice sidecar 8081 /voice/volume"],
  }),
  tool({
    toolId: "rana_join_voice",
    pluginId: "rana-music-tools",
    purpose: "Join the requester's current Discord voice channel through the shared coordinator.",
    request: { required: ["guild_id"], optional: ["requester_id", "channel_id"], schemaStatus: "RETRIEVED" },
    response: { kind: "structured", fields: ["status", "voice_status", "error"] },
    state: { model: ["shared-resource"], sharedState: true, isolation: ["guildId", "voiceChannelId", "requesterId", "voiceConnectionOwner"] },
    permissions: "Requester must have a current voice-channel context.",
    timeout: { sidecarMs: 12000, schemaStatus: "RETRIEVED" },
    errors: ["missing_requester", "not_in_voice", "not_in_guild", "unavailable", "timeout", "error"],
    dependency: ["shared voice sidecar 8081 /voice/join"],
  }),
  tool({
    toolId: "rana_leave_voice",
    pluginId: "rana-music-tools",
    purpose: "Leave the shared Discord voice channel.",
    request: { required: ["guild_id"], optional: [], schemaStatus: "RETRIEVED" },
    response: { kind: "structured", fields: ["status", "voice_status", "error"] },
    state: { model: ["shared-resource"], sharedState: true, isolation: ["guildId", "voiceConnectionOwner"] },
    permissions: "Current voice-control context.",
    timeout: { sidecarMs: 12000, schemaStatus: "RETRIEVED" },
    errors: ["unavailable", "timeout", "error"],
    dependency: ["shared voice sidecar 8081 /voice/leave"],
  }),
  tool({
    toolId: "ollama_web_search",
    pluginId: "openclaw-web-search",
    purpose: "Search current external information through the local Ollama web-search API.",
    request: { required: ["query"], optional: [], schemaStatus: "RETRIEVED" },
    response: { kind: "structured_text", fields: ["title", "url", "content"], sourceRefs: true },
    state: { model: ["stateless"], sharedState: false, isolation: ["requestId"] },
    permissions: "Tool policy and explicit/current lookup intent.",
    timeout: { requestMs: 15000, schemaStatus: "RETRIEVED" },
    errors: ["invalid_query", "auth_failed", "forbidden", "unavailable", "timeout", "error"],
    dependency: ["Ollama 11434 /api/experimental/web_search"],
  }),
  tool({
    toolId: "ollama_web_fetch",
    pluginId: "openclaw-web-search",
    purpose: "Fetch a web page through the local Ollama web-fetch API.",
    request: { required: ["url"], optional: [], schemaStatus: "RETRIEVED" },
    response: { kind: "structured_text", fields: ["title", "content", "links"], sourceRefs: true },
    state: { model: ["stateless"], sharedState: false, isolation: ["requestId"] },
    permissions: "Tool policy and current lookup intent.",
    timeout: { requestMs: 15000, schemaStatus: "RETRIEVED" },
    errors: ["invalid_url", "auth_failed", "forbidden", "unavailable", "timeout", "error"],
    dependency: ["Ollama 11434 /api/experimental/web_fetch"],
  }),
  tool({
    toolId: "browser",
    pluginId: "browser",
    purpose: "Bundled browser interaction tool.",
    request: { status: "UNVERIFIED: bundled plugin schema not expanded by local registry", required: [], optional: [], schemaStatus: "UNVERIFIED" },
    response: { status: "UNVERIFIED: bundled plugin schema not expanded", kind: "structured" },
    state: { model: ["session-scoped"], sharedState: true, isolation: ["browserSession", "requestId"] },
    permissions: "OpenClaw tool policy and browser session access.",
    timeout: { value: "UNVERIFIED" },
    errors: ["unavailable", "timeout", "error"],
    dependency: ["bundled OpenClaw browser plugin"],
  }),
  tool({
    toolId: "codex_threads",
    pluginId: "codex",
    purpose: "Bundled Codex thread operations.",
    request: { status: "UNVERIFIED: bundled plugin schema not expanded by local registry", required: [], optional: [], schemaStatus: "UNVERIFIED" },
    response: { status: "UNVERIFIED: bundled plugin schema not expanded", kind: "structured" },
    state: { model: ["shared-resource", "session-scoped"], sharedState: true, isolation: ["threadId", "requestId"] },
    permissions: "OpenClaw tool policy and thread permissions.",
    timeout: { value: "UNVERIFIED" },
    errors: ["forbidden", "unavailable", "timeout", "error"],
    dependency: ["global Codex plugin"],
  }),
  tool({
    toolId: "memory_get",
    pluginId: "memory-core",
    purpose: "Bundled memory retrieval operation.",
    request: { status: "UNVERIFIED: bundled plugin schema not expanded by local registry", required: [], optional: [], schemaStatus: "UNVERIFIED" },
    response: { status: "UNVERIFIED: bundled plugin schema not expanded", kind: "structured" },
    state: { model: ["shared-resource", "session-scoped"], sharedState: true, isolation: ["agentId", "sessionKey", "requesterId"] },
    permissions: "OpenClaw tool policy and memory scope.",
    timeout: { value: "UNVERIFIED" },
    errors: ["forbidden", "unavailable", "timeout", "error"],
    dependency: ["bundled memory-core plugin"],
  }),
  tool({
    toolId: "memory_search",
    pluginId: "memory-core",
    purpose: "Bundled memory search operation.",
    request: { status: "UNVERIFIED: bundled plugin schema not expanded by local registry", required: [], optional: [], schemaStatus: "UNVERIFIED" },
    response: { status: "UNVERIFIED: bundled plugin schema not expanded", kind: "structured" },
    state: { model: ["shared-resource", "session-scoped"], sharedState: true, isolation: ["agentId", "sessionKey", "requesterId"] },
    permissions: "OpenClaw tool policy and memory scope.",
    timeout: { value: "UNVERIFIED" },
    errors: ["forbidden", "unavailable", "timeout", "error"],
    dependency: ["bundled memory-core plugin"],
  }),
  tool({
    toolId: "node_inference",
    pluginId: "ollama",
    purpose: "Bundled local inference operation.",
    request: { status: "UNVERIFIED: bundled plugin schema not expanded by local registry", required: [], optional: [], schemaStatus: "UNVERIFIED" },
    response: { status: "UNVERIFIED: bundled plugin schema not expanded", kind: "structured" },
    state: { model: ["shared-resource"], sharedState: true, isolation: ["requestId", "sessionKey"] },
    permissions: "OpenClaw tool policy and model-provider policy.",
    timeout: { value: "UNVERIFIED" },
    errors: ["unavailable", "timeout", "error"],
    dependency: ["bundled Ollama plugin"],
  }),
]);

export const TOOL_REGISTRY_IDS = Object.freeze(TOOL_REGISTRY.map((entry) => entry.toolId));

export function getToolRegistry() {
  return TOOL_REGISTRY;
}

export function getToolRegistryEntry(toolId) {
  const id = String(toolId || "").trim();
  return TOOL_REGISTRY.find((entry) => entry.toolId === id) || null;
}

export function compareToolRegistryIds(activeToolIds = []) {
  const active = new Set((Array.isArray(activeToolIds) ? activeToolIds : []).map((id) => String(id || "").trim()).filter(Boolean));
  const registered = new Set(TOOL_REGISTRY_IDS);
  return {
    missing: [...active].filter((id) => !registered.has(id)).sort(),
    stale: [...registered].filter((id) => !active.has(id)).sort(),
  };
}
